project('SPW-LearnCPPTheHardWay', 'cpp',
    default_options: ['cpp_std=c++20'])

fmt = dependency('fmt')

executable('ex02', 'ex02.cpp')
executable('ex05', 'ex05.cpp')
executable('ex08', 'ex08.cpp')
executable('ex09', 'ex09.cpp', dependencies: fmt)
executable('ex13', 'ex13.cpp', dependencies: fmt)
executable('ex14', 'ex14.cpp', dependencies: fmt)
executable('ex16', 'ex16.cpp', dependencies: fmt)
executable('ex20_v1', 'ex20_v1.cpp', dependencies: fmt)
executable('ex20_v2', 'ex20_v2.cpp', dependencies: fmt)
executable('ex21', 'ex21.cpp', dependencies: fmt)
executable('ex22', 'ex22.cpp', dependencies: fmt)
